[package]
name = "marc-rs-derive"
version = "0.1.1"
edition = "2021"
authors = ["Jean Collonvillé <jcollonville@b-612.fr>"]
description = "Derive macros for marc-rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jcollonville/marc-rs"
keywords = ["marc", "derive", "macro"]
categories = ["encoding", "parsing"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
