use crate::datatypes::{PersonalNameType, OrganizationNameType};
use crate::formats::{BlockId, FieldType, SubfieldMapping, TagDescriptor, FormatDescriptor};

/// Singleton instance for the UNIMARC semantic format.
pub struct UnimarcFormat;

pub static UNIMARC_FORMAT: UnimarcFormat = UnimarcFormat;

// ── Shared subfield mappings (reused across tags) ─────────────────────────

const SF_A: &[SubfieldMapping] = &[
    SubfieldMapping { code: 'a', name: "value", repeatable: false },
];

const SF_NOTE: &[SubfieldMapping] = &[
    SubfieldMapping { code: 'a', name: "text", repeatable: false },
    SubfieldMapping { code: 'u', name: "uri", repeatable: false },
];

const SF_LINKING: &[SubfieldMapping] = &[
    SubfieldMapping { code: 't', name: "title", repeatable: false },
    SubfieldMapping { code: 'v', name: "volume", repeatable: false },
    SubfieldMapping { code: 'w', name: "record_control_number", repeatable: false },
    SubfieldMapping { code: 'x', name: "issn", repeatable: false },
    SubfieldMapping { code: 'z', name: "isbn", repeatable: false },
    SubfieldMapping { code: '1', name: "link_identifier", repeatable: false },
];

const SF_PERSONAL_NAME: &[SubfieldMapping] = &[
    SubfieldMapping { code: 'a', name: "surname", repeatable: false },
    SubfieldMapping { code: 'b', name: "forenames", repeatable: false },
    SubfieldMapping { code: 'c', name: "additions_to_name", repeatable: false },
    SubfieldMapping { code: 'd', name: "roman_numerals", repeatable: false },
    SubfieldMapping { code: 'f', name: "dates", repeatable: false },
    SubfieldMapping { code: 'g', name: "alternative_name", repeatable: false },
    SubfieldMapping { code: '4', name: "relator_code", repeatable: true },
];

const SF_CORPORATE_NAME: &[SubfieldMapping] = &[
    SubfieldMapping { code: 'a', name: "name", repeatable: false },
    SubfieldMapping { code: 'b', name: "subordinate_unit", repeatable: true },
    SubfieldMapping { code: 'c', name: "location", repeatable: false },
    SubfieldMapping { code: 'd', name: "date", repeatable: false },
    SubfieldMapping { code: 'e', name: "relator_term", repeatable: false },
    SubfieldMapping { code: '4', name: "relator_code", repeatable: true },
];

const SF_UNIFORM_TITLE: &[SubfieldMapping] = &[
    SubfieldMapping { code: 'a', name: "title", repeatable: false },
    SubfieldMapping { code: 'd', name: "date", repeatable: false },
    SubfieldMapping { code: 'f', name: "date_of_work", repeatable: false },
    SubfieldMapping { code: 'l', name: "language", repeatable: false },
    SubfieldMapping { code: 'n', name: "number", repeatable: false },
    SubfieldMapping { code: 'p', name: "name_of_part", repeatable: false },
];

const SF_SUBJECT: &[SubfieldMapping] = &[
    SubfieldMapping { code: 'a', name: "term", repeatable: false },
    SubfieldMapping { code: 'j', name: "form_subdivision", repeatable: true },
    SubfieldMapping { code: 'x', name: "general_subdivision", repeatable: true },
    SubfieldMapping { code: 'y', name: "chronological_subdivision", repeatable: true },
    SubfieldMapping { code: 'z', name: "geographic_subdivision", repeatable: true },
    SubfieldMapping { code: '2', name: "source", repeatable: false },
    SubfieldMapping { code: '3', name: "authority_number", repeatable: false },
];

pub const UNIMARC_DESCRIPTORS: &[TagDescriptor] = &[
    // ── Bloc 0 – Identification ─────────────────────────────────────────
    TagDescriptor { tag: "001", block: BlockId::Identification, field: "record_identifier",
        field_type: FieldType::SimpleString, is_control: true, subfield_map: &[] },
    TagDescriptor { tag: "003", block: BlockId::Identification, field: "agency_identifier",
        field_type: FieldType::SimpleString, is_control: true, subfield_map: &[] },
    TagDescriptor { tag: "005", block: BlockId::Identification, field: "record_version_date",
        field_type: FieldType::SimpleString, is_control: true, subfield_map: &[] },
    TagDescriptor { tag: "010", block: BlockId::Identification, field: "isbn",
        field_type: FieldType::Isbn, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "value", repeatable: false },
            SubfieldMapping { code: 'b', name: "qualification", repeatable: false },
            SubfieldMapping { code: 'd', name: "price_or_acquisition", repeatable: false },
            SubfieldMapping { code: 'z', name: "canceled_invalid", repeatable: true },
        ] },
    TagDescriptor { tag: "011", block: BlockId::Identification, field: "issn",
        field_type: FieldType::SimpleString, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "value", repeatable: false },
            SubfieldMapping { code: 'x', name: "canceled", repeatable: true },
        ] },
    TagDescriptor { tag: "012", block: BlockId::Identification, field: "book_fingerprint",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "013", block: BlockId::Identification, field: "technical_report_number",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "014", block: BlockId::Identification, field: "asin_number",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "015", block: BlockId::Identification, field: "national_bibliography_number",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "016", block: BlockId::Identification, field: "national_library_record_number",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "017", block: BlockId::Identification, field: "legal_deposit_number",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "020", block: BlockId::Identification, field: "lccn",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "021", block: BlockId::Identification, field: "french_legal_deposit_number",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "022", block: BlockId::Identification, field: "government_document_number",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "035", block: BlockId::Identification, field: "system_control_number",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "036", block: BlockId::Identification, field: "music_publisher_number",
        field_type: FieldType::SimpleString, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "number", repeatable: false },
            SubfieldMapping { code: 'b', name: "publisher", repeatable: false },
        ] },
    TagDescriptor { tag: "040", block: BlockId::Identification, field: "coden",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "071", block: BlockId::Identification, field: "music_plate_number",
        field_type: FieldType::SimpleString, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "number", repeatable: false },
            SubfieldMapping { code: 'b', name: "publisher", repeatable: false },
        ] },
    TagDescriptor { tag: "072", block: BlockId::Identification, field: "ismn",
        field_type: FieldType::SimpleString, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "value", repeatable: false },
            SubfieldMapping { code: '2', name: "scheme", repeatable: false },
        ] },
    TagDescriptor { tag: "073", block: BlockId::Identification, field: "ean_gtin",
        field_type: FieldType::SimpleString, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "value", repeatable: false },
            SubfieldMapping { code: '2', name: "scheme", repeatable: false },
        ] },

    // ── Bloc 1 – Informations codées ────────────────────────────────────
    TagDescriptor { tag: "100", block: BlockId::CodedInformation, field: "general_processing_data",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "101", block: BlockId::CodedInformation, field: "language_of_resource",
        field_type: FieldType::Language, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "language_code", repeatable: true },
            SubfieldMapping { code: 'c', name: "language_of_original", repeatable: true },
        ] },
    TagDescriptor { tag: "102", block: BlockId::CodedInformation, field: "country_of_publication",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "105", block: BlockId::CodedInformation, field: "coded_text_monograph",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "106", block: BlockId::CodedInformation, field: "coded_document_form",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "110", block: BlockId::CodedInformation, field: "coded_serial_publication",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "115", block: BlockId::CodedInformation, field: "coded_video_projected_image",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "116", block: BlockId::CodedInformation, field: "coded_still_image",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "117", block: BlockId::CodedInformation, field: "coded_three_dimensional_material",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "120", block: BlockId::CodedInformation, field: "coded_cartographic_general",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "121", block: BlockId::CodedInformation, field: "coded_cartographic_earth_image",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "122", block: BlockId::CodedInformation, field: "coded_time_period",
        field_type: FieldType::StringList, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "123", block: BlockId::CodedInformation, field: "coded_cartographic_scale",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "124", block: BlockId::CodedInformation, field: "coded_cartographic_specific",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "125", block: BlockId::CodedInformation, field: "coded_printed_music",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "126", block: BlockId::CodedInformation, field: "coded_music_recording",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "127", block: BlockId::CodedInformation, field: "coded_non_music_sound",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "128", block: BlockId::CodedInformation, field: "coded_music_general",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "130", block: BlockId::CodedInformation, field: "coded_microform",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "131", block: BlockId::CodedInformation, field: "coded_cartographic_electronic",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "135", block: BlockId::CodedInformation, field: "coded_electronic_resource",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "140", block: BlockId::CodedInformation, field: "coded_early_printed_book",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "141", block: BlockId::CodedInformation, field: "coded_early_book_copy",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },

    // ── Bloc 2 – Description ─────────────────────────────────────────────
    TagDescriptor { tag: "200", block: BlockId::Description, field: "title_statement",
        field_type: FieldType::TitleStatement, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "title", repeatable: false },
            SubfieldMapping { code: 'b', name: "general_material_designation", repeatable: false },
            SubfieldMapping { code: 'c', name: "other_title_information", repeatable: false },
            SubfieldMapping { code: 'd', name: "parallel_title", repeatable: false },
            SubfieldMapping { code: 'e', name: "other_title_info_2", repeatable: false },
            SubfieldMapping { code: 'f', name: "first_responsibility", repeatable: false },
            SubfieldMapping { code: 'g', name: "other_responsibility", repeatable: false },
            SubfieldMapping { code: 'h', name: "number_of_part", repeatable: false },
            SubfieldMapping { code: 'i', name: "name_of_part", repeatable: false },
        ] },
    TagDescriptor { tag: "204", block: BlockId::Description, field: "title_statement_obsolete",
        field_type: FieldType::TitleStatement, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "title", repeatable: false },
            SubfieldMapping { code: 'f', name: "first_responsibility", repeatable: false },
        ] },
    TagDescriptor { tag: "205", block: BlockId::Description, field: "edition_statement",
        field_type: FieldType::EditionStatement, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "edition", repeatable: false },
            SubfieldMapping { code: 'b', name: "remainder", repeatable: false },
        ] },
    TagDescriptor { tag: "206", block: BlockId::Description, field: "cartographic_mathematical_data",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "207", block: BlockId::Description, field: "serial_numbering",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "208", block: BlockId::Description, field: "music_presentation_statement",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "210", block: BlockId::Description, field: "publication_distribution_imprint",
        field_type: FieldType::Publication, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "place", repeatable: true },
            SubfieldMapping { code: 'c', name: "publisher", repeatable: true },
            SubfieldMapping { code: 'd', name: "date", repeatable: true },
            SubfieldMapping { code: 'e', name: "manufacturing_place", repeatable: true },
            SubfieldMapping { code: 'g', name: "manufacturing_date", repeatable: true },
        ] },
    TagDescriptor { tag: "211", block: BlockId::Description, field: "open_access_zone",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "215", block: BlockId::Description, field: "physical_description",
        field_type: FieldType::PhysicalDescription, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "extent", repeatable: false },
            SubfieldMapping { code: 'c', name: "other_physical_details", repeatable: false },
            SubfieldMapping { code: 'd', name: "dimensions", repeatable: false },
            SubfieldMapping { code: 'e', name: "accompanying_material", repeatable: false },
        ] },
    TagDescriptor { tag: "225", block: BlockId::Description, field: "series_statement",
        field_type: FieldType::SeriesStatement, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "statement", repeatable: false },
            SubfieldMapping { code: 'v', name: "volume", repeatable: false },
            SubfieldMapping { code: 'x', name: "issn", repeatable: false },
        ] },
    TagDescriptor { tag: "230", block: BlockId::Description, field: "electronic_resource_characteristics",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "240", block: BlockId::Description, field: "uniform_title_isbd",
        field_type: FieldType::UniformTitle, is_control: false, subfield_map: SF_UNIFORM_TITLE },

    // ── Bloc 3 – Notes ───────────────────────────────────────────────────
    TagDescriptor { tag: "300", block: BlockId::Notes, field: "general_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "301", block: BlockId::Notes, field: "identifying_bibliographic_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "302", block: BlockId::Notes, field: "nature_scope_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "303", block: BlockId::Notes, field: "bibliographic_sources_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "304", block: BlockId::Notes, field: "title_responsibility_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "305", block: BlockId::Notes, field: "edition_history_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "306", block: BlockId::Notes, field: "publication_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "307", block: BlockId::Notes, field: "physical_description_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "308", block: BlockId::Notes, field: "series_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "310", block: BlockId::Notes, field: "serial_publication_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "311", block: BlockId::Notes, field: "related_resources_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "312", block: BlockId::Notes, field: "title_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "313", block: BlockId::Notes, field: "subject_coverage_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "314", block: BlockId::Notes, field: "persons_organizations_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "315", block: BlockId::Notes, field: "document_characteristics_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "316", block: BlockId::Notes, field: "copy_specific_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "317", block: BlockId::Notes, field: "provenance_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "318", block: BlockId::Notes, field: "action_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "320", block: BlockId::Notes, field: "internal_bibliography_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "321", block: BlockId::Notes, field: "summary_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "322", block: BlockId::Notes, field: "cast_credits_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "323", block: BlockId::Notes, field: "cast_distribution_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "324", block: BlockId::Notes, field: "reproduction_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "325", block: BlockId::Notes, field: "original_of_reproduction_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "326", block: BlockId::Notes, field: "publication_frequency_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "327", block: BlockId::Notes, field: "contents_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "328", block: BlockId::Notes, field: "dissertation_thesis_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "330", block: BlockId::Notes, field: "native_language_summary_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "332", block: BlockId::Notes, field: "preferred_citation_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "333", block: BlockId::Notes, field: "audience_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "336", block: BlockId::Notes, field: "content_type_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "337", block: BlockId::Notes, field: "media_type_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },
    TagDescriptor { tag: "338", block: BlockId::Notes, field: "carrier_type_note",
        field_type: FieldType::NoteEntry, is_control: false, subfield_map: SF_NOTE },

    // ── Bloc 4 – Liens ───────────────────────────────────────────────────
    TagDescriptor { tag: "410", block: BlockId::Links, field: "link_series",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "411", block: BlockId::Links, field: "link_subseries",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "421", block: BlockId::Links, field: "link_supplement",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "422", block: BlockId::Links, field: "link_supplement_parent",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "423", block: BlockId::Links, field: "link_published_with",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "430", block: BlockId::Links, field: "link_other_edition_same_medium",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "431", block: BlockId::Links, field: "link_other_edition_other_medium",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "432", block: BlockId::Links, field: "link_replaced_by",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "433", block: BlockId::Links, field: "link_replaces",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "434", block: BlockId::Links, field: "link_absorbs",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "435", block: BlockId::Links, field: "link_absorbed_by",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "436", block: BlockId::Links, field: "link_split_into",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "437", block: BlockId::Links, field: "link_merged_from",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "440", block: BlockId::Links, field: "link_section_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "441", block: BlockId::Links, field: "link_other_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "442", block: BlockId::Links, field: "link_key_title_qualifier",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "443", block: BlockId::Links, field: "link_abbreviated_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "444", block: BlockId::Links, field: "link_expanded_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "445", block: BlockId::Links, field: "link_title_variant",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "446", block: BlockId::Links, field: "link_offprint_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "447", block: BlockId::Links, field: "link_part_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "448", block: BlockId::Links, field: "link_reproduced_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "451", block: BlockId::Links, field: "link_same_pub_other_medium",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "452", block: BlockId::Links, field: "link_electronic_version",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "453", block: BlockId::Links, field: "link_translated_to",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "454", block: BlockId::Links, field: "link_translated_from",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "455", block: BlockId::Links, field: "link_reproduction_of",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "456", block: BlockId::Links, field: "link_reproduced_in",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "461", block: BlockId::Links, field: "link_parent_set",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "462", block: BlockId::Links, field: "link_subset",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "463", block: BlockId::Links, field: "link_analytic_part",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "464", block: BlockId::Links, field: "link_component_part",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "470", block: BlockId::Links, field: "link_reviewed_resource",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "481", block: BlockId::Links, field: "link_bound_with",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "482", block: BlockId::Links, field: "link_bound_set",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },
    TagDescriptor { tag: "488", block: BlockId::Links, field: "link_other_relationship",
        field_type: FieldType::LinkingEntry, is_control: false, subfield_map: SF_LINKING },

    // ── Bloc 5 – Titres associés ─────────────────────────────────────────
    TagDescriptor { tag: "500", block: BlockId::AssociatedTitles, field: "uniform_title",
        field_type: FieldType::UniformTitle, is_control: false, subfield_map: SF_UNIFORM_TITLE },
    TagDescriptor { tag: "501", block: BlockId::AssociatedTitles, field: "collective_uniform_title",
        field_type: FieldType::UniformTitle, is_control: false, subfield_map: SF_UNIFORM_TITLE },
    TagDescriptor { tag: "503", block: BlockId::AssociatedTitles, field: "uniform_title_variant",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "510", block: BlockId::AssociatedTitles, field: "title_access_point",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "512", block: BlockId::AssociatedTitles, field: "cover_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "513", block: BlockId::AssociatedTitles, field: "running_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "514", block: BlockId::AssociatedTitles, field: "spine_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "515", block: BlockId::AssociatedTitles, field: "caption_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "516", block: BlockId::AssociatedTitles, field: "label_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "517", block: BlockId::AssociatedTitles, field: "other_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "518", block: BlockId::AssociatedTitles, field: "jacket_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "519", block: BlockId::AssociatedTitles, field: "analytical_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "520", block: BlockId::AssociatedTitles, field: "former_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "530", block: BlockId::AssociatedTitles, field: "key_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "531", block: BlockId::AssociatedTitles, field: "abbreviated_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "532", block: BlockId::AssociatedTitles, field: "expanded_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "540", block: BlockId::AssociatedTitles, field: "uniform_title_added_entry",
        field_type: FieldType::UniformTitle, is_control: false, subfield_map: SF_UNIFORM_TITLE },
    TagDescriptor { tag: "541", block: BlockId::AssociatedTitles, field: "translated_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "545", block: BlockId::AssociatedTitles, field: "section_part_title",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },

    // ── Bloc 6 – Analyse matière ─────────────────────────────────────────
    TagDescriptor { tag: "600", block: BlockId::SubjectAnalysis, field: "subject_person_name",
        field_type: FieldType::PersonalName, is_control: false, subfield_map: SF_PERSONAL_NAME },
    TagDescriptor { tag: "601", block: BlockId::SubjectAnalysis, field: "subject_corporate_name",
        field_type: FieldType::CorporateName, is_control: false, subfield_map: SF_CORPORATE_NAME },
    TagDescriptor { tag: "602", block: BlockId::SubjectAnalysis, field: "subject_family_name",
        field_type: FieldType::PersonalName, is_control: false, subfield_map: SF_PERSONAL_NAME },
    TagDescriptor { tag: "604", block: BlockId::SubjectAnalysis, field: "subject_name_title",
        field_type: FieldType::SubjectEntry, is_control: false, subfield_map: SF_SUBJECT },
    TagDescriptor { tag: "605", block: BlockId::SubjectAnalysis, field: "subject_title",
        field_type: FieldType::SubjectEntry, is_control: false, subfield_map: SF_SUBJECT },
    TagDescriptor { tag: "606", block: BlockId::SubjectAnalysis, field: "subject_topical_term",
        field_type: FieldType::SubjectEntry, is_control: false, subfield_map: SF_SUBJECT },
    TagDescriptor { tag: "607", block: BlockId::SubjectAnalysis, field: "subject_geographic_name",
        field_type: FieldType::SubjectEntry, is_control: false, subfield_map: SF_SUBJECT },
    TagDescriptor { tag: "608", block: BlockId::SubjectAnalysis, field: "subject_genre_form",
        field_type: FieldType::StringList, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "610", block: BlockId::SubjectAnalysis, field: "subject_uncontrolled_term",
        field_type: FieldType::StringList, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "615", block: BlockId::SubjectAnalysis, field: "subject_controlled_term",
        field_type: FieldType::SubjectEntry, is_control: false, subfield_map: SF_SUBJECT },
    TagDescriptor { tag: "616", block: BlockId::SubjectAnalysis, field: "subject_trademark",
        field_type: FieldType::StringList, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "620", block: BlockId::SubjectAnalysis, field: "subject_place_access",
        field_type: FieldType::SubjectEntry, is_control: false, subfield_map: SF_SUBJECT },
    TagDescriptor { tag: "621", block: BlockId::SubjectAnalysis, field: "subject_action_place",
        field_type: FieldType::SubjectEntry, is_control: false, subfield_map: SF_SUBJECT },
    TagDescriptor { tag: "626", block: BlockId::SubjectAnalysis, field: "subject_music_term",
        field_type: FieldType::StringList, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "660", block: BlockId::SubjectAnalysis, field: "geographic_area_code",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "661", block: BlockId::SubjectAnalysis, field: "subject_period_code",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "676", block: BlockId::SubjectAnalysis, field: "dewey_classification",
        field_type: FieldType::DeweyClassification, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "number", repeatable: true },
            SubfieldMapping { code: 'v', name: "edition", repeatable: false },
        ] },
    TagDescriptor { tag: "680", block: BlockId::SubjectAnalysis, field: "lc_classification",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "686", block: BlockId::SubjectAnalysis, field: "other_classification",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "690", block: BlockId::SubjectAnalysis, field: "local_subject_heading",
        field_type: FieldType::StringList, is_control: false, subfield_map: SF_A },

    // ── Bloc 7 – Responsabilité intellectuelle ───────────────────────────
    TagDescriptor { tag: "700", block: BlockId::IntellectualResponsibility, field: "main_entry_personal_name",
        field_type: FieldType::PersonalName, is_control: false, subfield_map: SF_PERSONAL_NAME },
    TagDescriptor { tag: "701", block: BlockId::IntellectualResponsibility, field: "added_entry_personal_name",
        field_type: FieldType::PersonalName, is_control: false, subfield_map: SF_PERSONAL_NAME },
    TagDescriptor { tag: "702", block: BlockId::IntellectualResponsibility, field: "added_entry_personal_name_alt",
        field_type: FieldType::PersonalName, is_control: false, subfield_map: SF_PERSONAL_NAME },
    TagDescriptor { tag: "710", block: BlockId::IntellectualResponsibility, field: "main_entry_corporate_name",
        field_type: FieldType::CorporateName, is_control: false, subfield_map: SF_CORPORATE_NAME },
    TagDescriptor { tag: "711", block: BlockId::IntellectualResponsibility, field: "added_entry_corporate_name",
        field_type: FieldType::CorporateName, is_control: false, subfield_map: SF_CORPORATE_NAME },
    TagDescriptor { tag: "712", block: BlockId::IntellectualResponsibility, field: "added_entry_corporate_name_alt",
        field_type: FieldType::CorporateName, is_control: false, subfield_map: SF_CORPORATE_NAME },
    TagDescriptor { tag: "720", block: BlockId::IntellectualResponsibility, field: "main_entry_family_name",
        field_type: FieldType::PersonalName, is_control: false, subfield_map: SF_PERSONAL_NAME },
    TagDescriptor { tag: "721", block: BlockId::IntellectualResponsibility, field: "added_entry_family_name",
        field_type: FieldType::PersonalName, is_control: false, subfield_map: SF_PERSONAL_NAME },
    TagDescriptor { tag: "722", block: BlockId::IntellectualResponsibility, field: "added_entry_family_name_alt",
        field_type: FieldType::PersonalName, is_control: false, subfield_map: SF_PERSONAL_NAME },
    TagDescriptor { tag: "730", block: BlockId::IntellectualResponsibility, field: "main_entry_uniform_title",
        field_type: FieldType::UniformTitle, is_control: false, subfield_map: SF_UNIFORM_TITLE },
    TagDescriptor { tag: "740", block: BlockId::IntellectualResponsibility, field: "added_entry_uniform_title",
        field_type: FieldType::UniformTitle, is_control: false, subfield_map: SF_UNIFORM_TITLE },

    // ── Bloc 8 – Usage international ────────────────────────────────────
    TagDescriptor { tag: "801", block: BlockId::InternationalUse, field: "cataloging_source",
        field_type: FieldType::GenericDataField, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "country", repeatable: false },
            SubfieldMapping { code: 'b', name: "agency", repeatable: false },
            SubfieldMapping { code: 'c', name: "date", repeatable: false },
            SubfieldMapping { code: 'g', name: "transcription_conventions", repeatable: false },
        ] },
    TagDescriptor { tag: "802", block: BlockId::InternationalUse, field: "issn_edition_identifier",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "830", block: BlockId::InternationalUse, field: "record_management_info",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "850", block: BlockId::InternationalUse, field: "holding_institution",
        field_type: FieldType::SimpleString, is_control: false, subfield_map: SF_A },
    TagDescriptor { tag: "852", block: BlockId::InternationalUse, field: "location_call_number",
        field_type: FieldType::GenericDataField, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "location", repeatable: false },
            SubfieldMapping { code: 'b', name: "sublocation", repeatable: false },
            SubfieldMapping { code: 'j', name: "call_number", repeatable: false },
        ] },
    TagDescriptor { tag: "856", block: BlockId::InternationalUse, field: "electronic_location_access",
        field_type: FieldType::SimpleString, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'u', name: "uri", repeatable: false },
            SubfieldMapping { code: 'z', name: "public_note", repeatable: false },
        ] },
    TagDescriptor { tag: "886", block: BlockId::InternationalUse, field: "unconverted_marc21_data",
        field_type: FieldType::GenericDataField, is_control: false, subfield_map: SF_A },

    // ── Bloc 9 – Usage local ─────────────────────────────────────────────
    TagDescriptor { tag: "995", block: BlockId::LocalUse, field: "local_use_field",
        field_type: FieldType::Specimen, is_control: false,
        subfield_map: &[
            SubfieldMapping { code: 'a', name: "library", repeatable: false },
            SubfieldMapping { code: 'b', name: "section", repeatable: false },
            SubfieldMapping { code: 'c', name: "sub_library", repeatable: false },
            SubfieldMapping { code: 'd', name: "section_code", repeatable: false },
            SubfieldMapping { code: 'e', name: "level_code", repeatable: false },
            SubfieldMapping { code: 'f', name: "barcode", repeatable: false },
            SubfieldMapping { code: 'k', name: "call_number", repeatable: false },
            SubfieldMapping { code: 'l', name: "inventory_number", repeatable: false },
            SubfieldMapping { code: 'm', name: "creation_date", repeatable: false },
            SubfieldMapping { code: 'n', name: "modification_date", repeatable: false },
            SubfieldMapping { code: 'o', name: "loan_date", repeatable: false },
            SubfieldMapping { code: 'p', name: "return_date", repeatable: false },
            SubfieldMapping { code: 'q', name: "acquisition_date", repeatable: false },
            SubfieldMapping { code: 'r', name: "item_type", repeatable: false },
            SubfieldMapping { code: 't', name: "record_control_number", repeatable: false },
            SubfieldMapping { code: 'v', name: "document_type", repeatable: false },
            SubfieldMapping { code: 'w', name: "circulation_status", repeatable: false },
        ] },
];

impl FormatDescriptor for UnimarcFormat {
    fn name(&self) -> &str { "unimarc" }

    fn tag_descriptor(&self, tag: &str) -> Option<&'static TagDescriptor> {
        UNIMARC_DESCRIPTORS.iter().find(|d| d.tag == tag)
    }

    fn field_type_to_tag(&self, field_type: FieldType) -> Vec<&'static TagDescriptor> {
        UNIMARC_DESCRIPTORS.iter().filter(|d| d.field_type == field_type).collect()
    }

    fn field_to_tag(&self, block: BlockId, field: &str) -> Option<&'static TagDescriptor> {
        UNIMARC_DESCRIPTORS.iter().find(|d| d.block == block && d.field == field)
    }

    fn all_descriptors(&self) -> &'static [TagDescriptor] {
        UNIMARC_DESCRIPTORS
    }

    fn personal_name_type_from_ind1(&self, _ind1: char) -> PersonalNameType {
        PersonalNameType::Surname
    }

    fn personal_name_type_to_ind1(&self, _name_type: &PersonalNameType) -> char {
        ' '
    }

    fn organization_name_type_from_ind1(&self, _ind1: char) -> OrganizationNameType {
        OrganizationNameType::DirectOrder
    }

    fn organization_name_type_to_ind1(&self, _name_type: &OrganizationNameType) -> char {
        ' '
    }
}
